
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: http://localhost:8442/realms/master
            authorities:
              - path: $.realm_access.roles
              - path: $.ressource_access.spring-addons-confidential.roles
            username-claim: preferred_username
        resourceserver:
          permit-all:
            - /users/me
logging:
  level:
    org.springframework.security: DEBUG
keycloak:
  auth-server-url: http://localhost:8442/realms/master/protocol/openid-connect/
  client_id: phuochuan_client
  grant_type: password
  server_url: http://localhost:8442/
  realm: master
  client_secret:

spring:
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


